### ISSUE TITLE
Container action is only supported on Linux

### ISSUE THREAD

**Issue by agam-mahajan-swiggy** [jesusvasquez333/verify-pr-label-action#7]
Integrated in my repo
```
runs-on: macos-latest
steps:
    - name: Verify Pull Request Labels
      uses: jesusvasquez333/verify-pr-label-action@v1.1.0
      with:
        github-token: '${{ secrets.GITHUBTOKEN }}'
        valid-labels: 'bug, enhancement'
```

 But getting error
`##[error]Container action is only supported on Linux`

Can you add support for mac-os?
